config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  resources :patch_notes
  resources :post_its, path: "notes"
  get "toolkit", to: "pages#toolkit"
  get "about", to: "pages#about"
  get "christmas_calendar", to: "pages#christmas_calendar", path: "christmas-calendar"
  get "add_calendar_number", to: "calendar_numbers#add_number"
  get "compose", to: "christmas_song#compose"
  post "check_sequence", to: "christmas_song#check_sequence"
  get "christmas_song", to: "christmas_song#christmas_song"
  devise_for :puddings
  resources :issues
  put "issue_resolve", to: "issues#resolve"
  resources :questions
  resources :answerings,        only: [:new, :create]
  get "settings", to: "settings#edit"
  resources :settings,          only: [:update]
  resources :songs,             only: [:index, :new, :create, :edit, :update, :destroy], path: "jukebox"
  resources :song_of_the_days,  only: [:index], path: "time-travel"
  get "song-of-the-day", to: "song_of_the_days#show", as: "song_of_the_day"
  resources :beers,             only: [:index, :new, :create, :edit, :update, :destroy], path: "tasting-center"
  resources :things,            only: [:index, :new, :create, :edit, :update, :destroy], path: "bucketlist"
  resources :holidays,          only: [:index, :show, :new, :create, :edit, :update, :destroy]
  get "change_status", to: "things#change_status"
  resources :tournaments,       only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :matches,           only: [:new, :create, :edit, :update, :destroy] do
    get :autocomplete_place, :on => :collection
  end
  resources :visited_places,    only: [:index, :new, :create, :destroy], path: "visited-places"

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/models/holiday.rb
# == Schema Information
#
# Table name: holidays
#
#  id         :integer          not null, primary key
#  date       :date
#  name       :string
#  message    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Holiday < ActiveRecord::Base

  validates_presence_of :name, :message, :date
  validates_length_of :name, :maximum => 15

  scope :order_by_date, -> { order(date: :asc) }

  def self.today
    Date.today.change(year: 2000)
  end

  def self.next
    today = Holiday.today
    return order_by_date.first if order_by_date.last.date < today
    order_by_date.each do |holiday|
      return holiday if holiday.date >= today
    end
  end

  def is_it_today?
    Date.today.change(year: 2000).midnight == date.midnight ? true : false
  end

  def next?
    self == Holiday.next ? true : false
  end

end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy, :change_status]
  before_action :check_resource_permission
  before_action :set_about_page, only: :index

  def index
    @holidays = Holiday.order_by_date
  end

  def show
    respond_to do |format|
      format.js
    end
  end

  def new
    @holiday = Holiday.new
  end

  def edit
  end

  def create
    @holiday = Holiday.new(holiday_params)
    @holiday.date = @holiday.date.change(year: 2000).midnight
    respond_to do |format|
      if @holiday.save
        format.html { redirect_to holidays_path, notice: 'Holiday was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to holidays_path, notice: 'Holiday was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: 'Holiday was successfully destroyed.' }
    end
  end


  private
    def set_holiday
      @holiday = Holiday.find(params[:id])
      # @holiday.date = @holiday.date.change(year: 2001) if @holiday.date < Holiday.today
    end

    def holiday_params
      params.require(:holiday).permit(:name, :date, :message)
    end

    def set_about_page
      @about_page = "<p>What use is of Holiday if we dont remember to celebrate it.</p>
                      <p>Smal portion of our best days we have written to remember.</p>
                      <p>Here they are, let's celebrate life :)</p>"
    end

end

app/helpers/holiday_helper.rb
module HolidayHelper
  def this_or_next_year(holiday)
    holiday.date <= Holiday.today ? Date.today.year+1 : Date.today.year
  end
end

app/views/holidays/_form.html.erb
<%= form_for @holiday, html: { class:"form" } do |f| %>
  <%= render partial: 'layouts/error_messages', as: :object, object: @holiday %>

  <div class="form-field">
    <div class="form-field-outer-wrapper--text_field">
      <div class="form-field-wrapper">
        <div class="form-field-label">Name</div>
        <%= f.text_field :name, placeholder: "Holiday name...", class: "text-field" %>
      </div>
    </div>
  </div>

  <div class="form-field">
    <div class="form-field-outer-wrapper--text_field">
      <div class="form-field-wrapper datetime-fields">
        <div class="form-field-label">Date</div>
        <div><%= f.date_select :date, { discard_year: true } %></div>
      </div>
    </div>
  </div>

  <div class="form-field">
    <div class="form-field-outer-wrapper--text_field">
      <div class="form-field-wrapper">
        <div class="form-field-label">Message</div>
        <%= f.text_field :message, placeholder: "Message...", class: "text-field" %>
      </div>
    </div>
  </div>

  <div class="form-field-outer-wrapper">
    <div class="form-field-wrapper">
      <%= f.submit "Submit", class: "button button-green" %>
      <%= link_to "Back", holidays_path, class: "button button-red" %>
    </div>
  </div>

<% end %>

app/views/holidays/_holiday.html.erb
<div class="holiday-wrapper">
  <%= link_to holiday, class: "holiday-outer-wrapper holiday-#{holiday.id}", remote: true do %>
  <!-- <div class="holiday-outer-wrapper"> -->
    <div class="holiday-inner-wrapper <%= "red-border" if holiday.next? %> <%= "blue-border" if holiday.next? %>">
      <div class="holiday-name"><%= holiday.name %></div>
      <div class="holiday-date-wrapper <%= "red-background" if holiday.next? %> <%= "blue-background" if holiday.next? %>">
        <div class="holiday-day"><%= holiday.date.strftime("%d.") %></div>
        <div class="holiday-month"><%= holiday.date.strftime("%B") %></div>
      </div>
    </div>
  <!-- </div> -->
  <% end %>
  <div class="holiday-buttons">
    <div class="holiday-buttons-outer-wrapper">
      <div class="holiday-buttons-inner-wrapper">
        <%= link_to "Edit", edit_holiday_path(holiday), class: "link-yellow" %>
        <%= link_to "Delete", holiday_path(holiday), method: :delete, class: "link-red", data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  </div>
</div>

app/views/holidays/edit.html.erb
<h1>Editing <%= @holiday.name %></h1>

<%= render 'form' %>

app/views/holidays/index.html.erb
<h1>Holidays</h1>
<div class="holiday-countdown">
  <%= render 'shared/countdown_clock', holiday: Holiday.next %>
</div>

<h1>Holidays</h1>
<div class="owl-carousel">
  <% @holidays.each do |holiday| %>
    <%= render 'holidays/holiday', holiday: holiday %>
  <% end %>
</div>
<div class="button button-blue what_is_this-button">What!?</div>
<%= link_to '+AddHoliday', new_holiday_path, class: "button button-green fixed-control" %>


<script>
  $(".owl-carousel").owlCarousel({
    loop:false,
    startPosition: $(".holiday-outer-wrapper").index($(".holiday-<%= Holiday.next.id %>").first()),
    responsive:{
        0:{
            items:1,
            loop:true
        },
        600:{
            items:2,
            loop:true
        },
        900:{
            items:3,
            loop:true
        },
        1200:{
            items:4,
            loop:true
        }
    }
  });
</script>

app/views/holidays/new.html.erb
<h1>New Holiday</h1>

<%= render 'form' %>

app/views/holidays/show.js.erb
$(".blue-background").removeClass("blue-background");
$(".blue-border").removeClass("blue-border");
$(".holiday-<%= @holiday.id %>").children(".holiday-inner-wrapper").addClass("blue-border");
$(".holiday-<%= @holiday.id %>").children(".holiday-inner-wrapper").children(".holiday-date-wrapper").addClass("blue-background");
$(".holiday-countdown").html("<%= j render 'shared/countdown_clock', holiday: @holiday %>");