config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  resources :patch_notes
  resources :post_its, path: "notes"
  get "toolkit", to: "pages#toolkit"
  get "about", to: "pages#about"
  get "christmas_calendar", to: "pages#christmas_calendar", path: "christmas-calendar"
  get "add_calendar_number", to: "calendar_numbers#add_number"
  get "compose", to: "christmas_song#compose"
  post "check_sequence", to: "christmas_song#check_sequence"
  get "christmas_song", to: "christmas_song#christmas_song"
  devise_for :puddings
  resources :issues
  put "issue_resolve", to: "issues#resolve"
  resources :questions
  resources :answerings,        only: [:new, :create]
  get "settings", to: "settings#edit"
  resources :settings,          only: [:update]
  resources :songs,             only: [:index, :new, :create, :edit, :update, :destroy], path: "jukebox"
  resources :song_of_the_days,  only: [:index], path: "time-travel"
  get "song-of-the-day", to: "song_of_the_days#show", as: "song_of_the_day"
  resources :beers,             only: [:index, :new, :create, :edit, :update, :destroy], path: "tasting-center"
  resources :things,            only: [:index, :new, :create, :edit, :update, :destroy], path: "bucketlist"
  resources :holidays,          only: [:index, :show, :new, :create, :edit, :update, :destroy]
  get "change_status", to: "things#change_status"
  resources :tournaments,       only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :matches,           only: [:new, :create, :edit, :update, :destroy] do
    get :autocomplete_place, :on => :collection
  end
  resources :visited_places,    only: [:index, :new, :create, :destroy], path: "visited-places"

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/models/issue.rb
# == Schema Information
#
# Table name: issues
#
#  id         :integer          not null, primary key
#  text       :string
#  resolved   :boolean          default(FALSE)
#  pudding_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Issue < ActiveRecord::Base
  belongs_to :pudding
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:edit, :update, :destroy, :resolve]
  before_action :set_about_page, only: :index

  def index
    @issues = Issue.all.order(created_at: :desc)
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = current_pudding.issues.build(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to issues_path, notice: 'Issue it was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to issues_path(@issue), notice: 'Issue was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue it was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def resolve
    @issue.resolved = params[:status] == "Resolve" ? true : false
    @issue.save
    respond_to do |format|
      @issue.resolved ? flash.now[:notice] = "Nice! You have resolved an issue." : flash.now[:notice] = "Issue is reopened."
      format.js
    end
  end

  private
    def set_issue
      @issue = Issue.find(params[:id])
    end

    def issue_params
      params.require(:issue).permit(:text)
    end

    def set_about_page
      @about_page = "<p>Here you can report problems that you encountered in our application.</p>
                      <p>... but not the problems you are having with your boyfriend.</p>
                      <p>If you really want it, i can make that too xD</p>"
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def resolve_action_text(issue)
    issue.resolved ? "Reopen" : "Resolve"
  end
end

app/views/issues/_form.html.erb
<%= form_for @issue, class: "form" do |f| %>

  <div class="form-field">
    <div class="form-field-outer-wrapper--text_field">
      <div class="form-field-wrapper">
        <div class="form-field-label">Tell us what's the problem?</div>
        <%= f.text_field :text, class: "text-field" %>
      </div>
    </div>
  </div>

  <div class="form-field">
    <div class="form-field-outer-wrapper">
      <div class="form-field-wrapper">
        <%= f.submit "Submit", class: "button button-green" %>
        <%= link_to 'Back', issues_path, class: "button button-red" %>
      </div>
    </div>
  </div>

<% end %>

app/views/issues/_issue.html.erb
<div class="issue-outer_wrapper">
  <div class="issue-wrapper">
    <div class="issue-reporter"><%= issue.pudding.name %> said <%= time_ago_in_words(issue.created_at) %> ago:</div>
    <p class="issue-text <%= "crossed" if issue.resolved %>"><em>"<%= issue.text %>"</em></p>
      <%= link_to "Edit", edit_issue_path(issue), class: "link-yellow" %>
      <%= link_to "Delete", issue_path(issue), method: :delete, data: {confirm: "Are you sure?"}, class: "link-red" %>
      <%= link_to resolve_action_text(issue), issue_resolve_path(id: issue, status: resolve_action_text(issue)), remote: true, method: :put, class: "link-green" %>
  </div>
</div>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>
<%= render 'form' %>

app/views/issues/index.html.erb
<h1>Issues</h1>
<div class="report-issue-button">
  <%= link_to "Report Issue", new_issue_path, class: "button button-green" %>
</div>
<div class="issues-wrapper">
  <% @issues.each do |issue| %>
    <div class="js_issue-<%= issue.id %>"><%= render 'issue', issue: issue %></div>
  <% end %>
</div>
<div class="button button-blue what_is_this-button">What!?</div>

app/views/issues/new.html.erb
<h1>Opening issue</h1>

<%= render 'form' %>

app/views/issues/resolve.js.erb
$(".js_issue-<%= @issue.id %>").html("<%= j render 'issues/issue', issue: @issue %>");