config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  resources :patch_notes
  resources :post_its, path: "notes"
  get "toolkit", to: "pages#toolkit"
  get "about", to: "pages#about"
  get "christmas_calendar", to: "pages#christmas_calendar", path: "christmas-calendar"
  get "add_calendar_number", to: "calendar_numbers#add_number"
  get "compose", to: "christmas_song#compose"
  post "check_sequence", to: "christmas_song#check_sequence"
  get "christmas_song", to: "christmas_song#christmas_song"
  devise_for :puddings
  resources :issues
  put "issue_resolve", to: "issues#resolve"
  resources :questions
  resources :answerings,        only: [:new, :create]
  get "settings", to: "settings#edit"
  resources :settings,          only: [:update]
  resources :songs,             only: [:index, :new, :create, :edit, :update, :destroy], path: "jukebox"
  resources :song_of_the_days,  only: [:index], path: "time-travel"
  get "song-of-the-day", to: "song_of_the_days#show", as: "song_of_the_day"
  resources :beers,             only: [:index, :new, :create, :edit, :update, :destroy], path: "tasting-center"
  resources :things,            only: [:index, :new, :create, :edit, :update, :destroy], path: "bucketlist"
  resources :holidays,          only: [:index, :show, :new, :create, :edit, :update, :destroy]
  get "change_status", to: "things#change_status"
  resources :tournaments,       only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :matches,           only: [:new, :create, :edit, :update, :destroy] do
    get :autocomplete_place, :on => :collection
  end
  resources :visited_places,    only: [:index, :new, :create, :destroy], path: "visited-places"

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/models/thing.rb
# == Schema Information
#
# Table name: things
#
#  id                    :integer          not null, primary key
#  description           :string
#  image                 :string
#  done                  :boolean          default(FALSE)
#  achievement_heaviness :integer
#  done_date             :datetime
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#

class Thing < ActiveRecord::Base

  scope :done, -> {where(done: true)}
  scope :to_do, -> {where(done: false)}


end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy, :change_status]
  before_action :check_resource_permission
  before_action :set_about_page, only: :index

  def index
    @things = params[:done]=="true" ? Thing.done : Thing.to_do
    @things = @things.where(achievement_heaviness: params[:achievement_heaviness]) if params[:achievement_heaviness] && params[:achievement_heaviness] != "0"
    respond_to do |format|
      format.js
      format.html
    end
  end

  def new
    @thing = Thing.new
  end

  def edit
  end

  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to things_path, notice: 'Thing was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to things_path, notice: 'Thing was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
    end
  end

  def change_status
    @thing.done = params[:status] == 'Done' ? true : false
    @thing.done_date = @thing.done ? DateTime.now : nil
    @thing.save
    respond_to do |format|
      @thing.done ? flash.now[:notice] = "Nice! You have done a thing." : flash.now[:notice] = "Thing is undone again."
      format.js
    end
  end

  private
    def set_thing
      @thing = Thing.find(params[:id])
    end

    def thing_params
      params.require(:thing).permit(:description, :achievement_heaviness)
    end

    def set_about_page
      @about_page = "<p>Here i made space for our things</p>
                      <p>Our bucketlist things</p>
                      <p>Where we can write our goals and dreams!</p>
                      <p>Who knows... maybe... one day... we will fulfill them aaaaall :D</p>"
    end

end

app/helpers/things_helper.rb
module ThingsHelper

  def achievement_heaviness_text(achievement_heaviness)
    case achievement_heaviness
    when 1
      "Very Easy"
    when 2
      "Easy"
    when 3
      "We Will Do It"
    when 4
      "We CAN Do it"
    when 5
      "One Day"
    end
  end

    def achievement_heaviness_color(achievement_heaviness)
    case achievement_heaviness
    when 1
      "#388e3c"
    when 2
      "#1976d2"
    when 3
      "#fbc02d"
    when 4
      "#f57c00"
    when 5
      "#c62828"
    end
  end

end

app/views/things/_form.html.erb
<%= form_for @thing, class: "form" do |f| %>

  <div class="form-field">
    <div class="form-field-outer-wrapper--text_field">
      <div class="form-field-wrapper">
        <div class="form-field-label">Describe a goal</div>
        <%= f.text_field :description, class: "text-field" %>
      </div>
    </div>
  </div>

  <div class="form-field">
    <div class="form-field-outer-wrapper--text_field">
      <div class="form-field-wrapper">
        <div class="form-field-label">How hard it is?</div>
        <% heaviness = [["Very easy","1"],["Easy","2"],["We will do it","3"],["We CAN do it!","4"],["One day","5"]] %>
        <%= f.select :achievement_heaviness, options_for_select(heaviness, f.object.achievement_heaviness), class: 'select' %>
      </div>
    </div>
  </div>

  <div class="form-field">
    <div class="form-field-outer-wrapper">
      <div class="form-field-wrapper">
        <%= f.submit "Submit", class: "button button-green" %>
        <%= link_to 'Back', things_path, class: "button button-red" %>
      </div>
    </div>
  </div>

<% end %>

app/views/things/_thing.html.erb
<div class="thing-done-date"><%= thing.done_date.strftime("%d.%B.%Y") if thing.done %></div>

<div class="thing-description"><p class="thing-description-<%= thing.description.size > 42 ? "small" : "normal" %> <%= thing.done ? "thing-description-line_through" : "" %>"><%= thing.description %></p></div>
<div class="thing-bottom-part">
  <div class="thing-hardness" style="color: <%= achievement_heaviness_color(thing.achievement_heaviness) %>"><%= achievement_heaviness_text(thing.achievement_heaviness) %></div>
  <%= link_to 'Edit', edit_thing_path(thing), class: "link-yellow" %>
  <%= link_to 'Destroy', thing, method: :delete, data: { confirm: 'Are you sure?' }, class: "link-red" %>
  <%= link_to "#{thing.done ? 'Undone' : 'Done'}", change_status_path(id: thing.id, status: "#{thing.done ? 'Undone' : 'Done'}"), class: "link-green", remote: true %>
</div>

app/views/things/_things.html.erb
<% @things.each do |thing| %>
  <div class="thing-outer-wrapper js_things-<%= thing.id %>">
    <div class="thing-wrapper js_thing-<%= thing.id %>">
      <%= render 'things/thing', thing: thing %>
    </div>
  </div>
<% end %>

app/views/things/change_status.js.erb
$(".js_thing-<%= @thing.id %>").html("<%= j render 'things/thing', thing: @thing %>");
$(".js_notices").html("<%= j render 'layouts/notices' %>");
$(".js_things-<%= @thing.id %>").fadeOut();

app/views/things/edit.html.erb
<h1>Editing Thing</h1>

<%= render 'form' %>

app/views/things/index.html.erb
<h1>To Do</h1>

<div class="resource-filter">
  <div class="resource-filter-outer-wrapper">
    <%= form_for things_path, id: "bucketlist-filter-form", remote: true, method: :get do |f| %>
      <div class="resource-filter-wrapper">
        <div class="resource-filter-element">
          <div class="resource-filter-button-label">By Doneness</div>
          <div class="btn-switch">
              <input type="radio" id="yes" name="done" value="true" class="btn-switch__radio btn-switch__radio_yes" />
              <input type="radio" checked id="no" name="done" value="false" class="btn-switch__radio btn-switch__radio_no" />
              <label for="yes" class="btn-switch__label btn-switch__label_yes"><span class="btn-switch__txt">Done</span></label>
              <label for="no" class="btn-switch__label btn-switch__label_no"><span class="btn-switch__txt">ToDo</span></label>
          </div>
        </div>

        <div class="resource-filter-element">
          <div class="resource-filter-button-label">By Hardeness</div>
          <select id="" name="achievement_heaviness" class="select" style="width: 130px;">
            <option selected value= 0>All Things</option>
            <option value= 1>Very Easy</option>
            <option value= 2>Easy</option>
            <option value= 3>We Will Do It</option>
            <option value= 4>We CAN Do It</option>
            <option value= 5>One day</option>
          </select>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="things-wrapper owl-carousel">
  <%= render 'things/things' %>
</div>

<div class="button button-blue what_is_this-button">What!?</div>
<%= link_to '+AddThing', new_thing_path, class: "button button-green fixed-control" %>

<script>
  $("input,select").change(function(){
    $(this).closest("form").submit();
  });
  $(".owl-carousel").owlCarousel({
    loop:false,
    responsive:{
        0:{
            items:1,
        },
        600:{
            items:1,
        },
        900:{
            items:1,
        },
        1200:{
            items:4,
        }
    }
  });
</script>

app/views/things/index.js.erb
$(".things-wrapper").html("<%= j render 'things/things' %>");
$(".owl-carousel").owlCarousel('destroy');
$(".owl-carousel").owlCarousel({
	loop:false,
	responsive:{
	    0:{
	        items:1,
	    },
	    600:{
	        items:1,
	    },
	    900:{
	        items:1,
	    },
	    1200:{
	        items:4,
	    }
	}
});

app/views/things/new.html.erb
<h1>New Thing</h1>

<%= render 'form' %>