config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  resources :patch_notes
  resources :post_its, path: "notes"
  get "toolkit", to: "pages#toolkit"
  get "about", to: "pages#about"
  get "christmas_calendar", to: "pages#christmas_calendar", path: "christmas-calendar"
  get "add_calendar_number", to: "calendar_numbers#add_number"
  get "compose", to: "christmas_song#compose"
  post "check_sequence", to: "christmas_song#check_sequence"
  get "christmas_song", to: "christmas_song#christmas_song"
  devise_for :puddings
  resources :issues
  put "issue_resolve", to: "issues#resolve"
  resources :questions
  resources :answerings,        only: [:new, :create]
  get "settings", to: "settings#edit"
  resources :settings,          only: [:update]
  resources :songs,             only: [:index, :new, :create, :edit, :update, :destroy], path: "jukebox"
  resources :song_of_the_days,  only: [:index], path: "time-travel"
  get "song-of-the-day", to: "song_of_the_days#show", as: "song_of_the_day"
  resources :beers,             only: [:index, :new, :create, :edit, :update, :destroy], path: "tasting-center"
  resources :things,            only: [:index, :new, :create, :edit, :update, :destroy], path: "bucketlist"
  resources :holidays,          only: [:index, :show, :new, :create, :edit, :update, :destroy]
  get "change_status", to: "things#change_status"
  resources :tournaments,       only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :matches,           only: [:new, :create, :edit, :update, :destroy] do
    get :autocomplete_place, :on => :collection
  end
  resources :visited_places,    only: [:index, :new, :create, :destroy], path: "visited-places"

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/models/post_it.rb
# == Schema Information
#
# Table name: post_its
#
#  id         :integer          not null, primary key
#  pudding_id :integer
#  message    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostIt < ActiveRecord::Base
  belongs_to :pudding

  validates_presence_of :message

  # def check_message
  #   if message.length < 37
  #     if message.split("\n").map{ |x| x.length < 13 }.include?(false)
  #       puts "false"
  #       errors.add(:message, 'error message')
  #     else
  #      true
  #     end
  #   else
  #     errors.add(:message, 'error message')
  #   end
  # end

end

app/controllers/post_its_controller.rb
class PostItsController < ApplicationController
  before_action :set_post_it, only: [:destroy]
  before_action :set_about_page, only: :index
  before_action :check_resource_permission

  def index
    @post_its = PostIt.all.order(created_at: :asc)
  end

  def new
    @post_it = PostIt.new
  end

  def create
    @post_it = PostIt.new(post_it_params)

    respond_to do |format|
      if @post_it.save
        format.html { redirect_to post_its_path, notice: 'Post it was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @post_it.destroy
    respond_to do |format|
      format.html { redirect_to post_its_url, notice: 'Post it was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post_it
      @post_it = PostIt.find(params[:id])
    end

    def post_it_params
      params.require(:post_it).permit(:pudding_id, :message)
    end

    def set_about_page
      @about_page = "<p>If you need more explanation about this</p>
                      <p>leave me a note and i'll contact you :P</p>"
    end
end

app/helpers/post_its_helper.rb
module PostItsHelper
end

app/views/post_its/_form.html.erb
<%= form_for @post_it, html: { class: "form" } do |f| %>
  <%= render partial: 'layouts/error_messages', as: :object, object: @post_it %>

  <%= f.hidden_field :pudding_id, value: current_pudding.id %>

  <%= f.text_area :message, class: "js_message", style: "opacity: 0; position: absolute; z-index: -9;" %>
  <div class="sticker sticker-color-<%= current_pudding.setting.post_it_color %>" style="margin: auto;"></div>

  <div class="form-field-outer-wrapper">
    <div class="form-field-wrapper">
      <%= f.submit "Submit", class: "button button-green" %>
      <%= link_to "Back", post_its_path, class: "button button-red" %>
    </div>
  </div>
<% end %>

<script>
$(function(){
  $('.js_message').focus();
});
$('.js_message').keyup(function(){
  var message = $('.js_message').val();
  $('.sticker').text(message);
});
$('.sticker').click(function(){
  $('.js_message').focus();
});

</script>

app/views/post_its/_note.html.erb
<div class="sticker sticker-color-<%= post_it.pudding.setting.post_it_color %>"><%= post_it.message %>
  <div class="date"><%= post_it.created_at.strftime("%H:%M  %d.%m.%Y") %></div>
  <%= link_to 'Delete', post_it, class: "link-red", method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/post_its/index.html.erb
<h1>Notes</h1>
<div class="form-field">
  <div class="form-field-outer-wrapper">
    <div class="form-field-wrapper">
      <div class="form-field-label">All Notes (<%= @post_its.size %>)</div>
    </div>
  </div>
</div>

<div class="desktop-only">
  <div class="sticker-wrapper">
    <% @post_its.each do |post_it| %>
      <div class="sticker sticker-color-<%= post_it.pudding.setting.post_it_color %>"><%= post_it.message %>
        <div class="date"><%= post_it.created_at.strftime("%H:%M  %d.%m.%Y") %></div>
        <%= link_to 'Delete', post_it, class: "link-red", method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </div>
</div>

<div class="mobile-only">
  <div class="sticker-wrapper owl-carousel">
    <% @post_its.each do |post_it| %>
      <div class="sticker sticker-color-<%= post_it.pudding.setting.post_it_color %>"><%= post_it.message %>
        <div class="date"><%= post_it.created_at.strftime("%H:%M  %d.%m.%Y") %></div>
        <%= link_to 'Delete', post_it, class: "link-red", method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </div>
</div>

<div class="button button-blue what_is_this-button">What!?</div>
<%= link_to '+AddNote', new_post_it_path, class: "button button-green fixed-control" %>

<script>
$(".owl-carousel").owlCarousel({
  loop:false,
  startPosition: <%= @post_its.size-1 %>,
  responsive:{
      0:{
          items:1,
      },
      600:{
          items:1,
      },
      900:{
          items:1,
      },
      1200:{
          items:4,
      }
  }
});	
</script>

app/views/post_its/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>